org: drowningtoast
app: itgg
service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    httpPort: 7071
    useChildProcesses: true
