import type { NextPage } from "next";
import Head from "next/head";
import Agenda from "../components/agenda/Agenda";
import { axiosBackendInstance } from "../components/axios/helper";
import GGDay from "../components/banner/GGDay";
import Tournament from "../components/banner/Tournament";
import Hero from "../components/landing/Hero";
import Scoreboard, { Team } from "../components/scoreboard/Scoreboard";

interface PropsA {
  teams?: Team[];
}

const Home: NextPage<PropsA> = ({ teams }) => {
  return (
    <div className="w-screen h-screen flex flex-col items-center">
      <Head>
        <title>ITGG 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="ITGG 2022" />
        <meta
          property="og:url"
          content="https://info-tech-gategame.vercel.app/"
        />
        <meta
          property="og:image"
          content="https://info-tech-gategame.vercel.app/assets/hero.png"
        />
        <meta
          property="og:description"
          content="มีเพื่อนตัดเพื่อน มีพี่ตัดพี่ เพราะคณะไอที กำลังจะลุกเป็นไฟ 🔥🔥🔥 กลับมาอีกครั้งสำหรับการมหกรรมแข่งขันที่ใหญ่ที่สุด Info Tech Gate Game 2022 ได้เริ่มต้นขึ้นแล้ว!"
        />
        <meta property="og:site_name" content="InfoTech GateGame 2022" />
      </Head>

      <main className="bg-dark w-full overflow-x-hidden min-h-screen grid place-items-center">
        <Hero />
        <Scoreboard teams={teams} />
        <Agenda />
        <GGDay />
        <Tournament />
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const response = await axiosBackendInstance.get("/point/compute");
  const teams = await axiosBackendInstance.get<any, { data: Team[] }>(
    "/point/teams"
  );

  return {
    props: {
      teams: JSON.parse(JSON.stringify(teams.data)),
    },
    revalidate: 300,
  };
};

export default Home;
